//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class company
{
    public int adcoid { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string company1 { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public Nullable<int> brandid { get; set; }
    public string type { get; set; }

    public virtual tblBrand tblBrand { get; set; }
}

public partial class ForgotPassRequest
{
    public string Id { get; set; }
    public Nullable<int> Uid { get; set; }
    public Nullable<System.DateTime> RequestDateTime { get; set; }

    public virtual User User { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class tblBrand
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblBrand()
    {
        this.companies = new HashSet<company>();
        this.tblProducts = new HashSet<tblProduct>();
        this.tblSizes = new HashSet<tblSize>();
        this.tblCategories = new HashSet<tblCategory>();
    }

    public int BrandID { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<company> companies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProduct> tblProducts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblSize> tblSizes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblCategory> tblCategories { get; set; }
}

public partial class tblCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblCategory()
    {
        this.tblProducts = new HashSet<tblProduct>();
        this.tblSizes = new HashSet<tblSize>();
        this.tblSubCategories = new HashSet<tblSubCategory>();
    }

    public int CatID { get; set; }
    public string CatName { get; set; }
    public Nullable<int> BrandID { get; set; }

    public virtual tblBrand tblBrand { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProduct> tblProducts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblSize> tblSizes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblSubCategory> tblSubCategories { get; set; }
}

public partial class tblGender
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblGender()
    {
        this.tblProducts = new HashSet<tblProduct>();
        this.tblSizes = new HashSet<tblSize>();
    }

    public int GenderID { get; set; }
    public string GenderName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProduct> tblProducts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblSize> tblSizes { get; set; }
}

public partial class tblProduct
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblProduct()
    {
        this.tblProductImages = new HashSet<tblProductImage>();
        this.tblProductSizeQuantities = new HashSet<tblProductSizeQuantity>();
        this.tblratings = new HashSet<tblrating>();
    }

    public int PID { get; set; }
    public string PName { get; set; }
    public Nullable<decimal> PPrice { get; set; }
    public Nullable<decimal> PSelPrice { get; set; }
    public Nullable<int> PBrandID { get; set; }
    public Nullable<int> PCategoryID { get; set; }
    public Nullable<int> PSubCatID { get; set; }
    public Nullable<int> PGender { get; set; }
    public string PDescription { get; set; }
    public string PProductDetails { get; set; }
    public string PMaterialCare { get; set; }
    public Nullable<int> FreeDelivery { get; set; }
    public Nullable<int> C30DayRet { get; set; }
    public Nullable<int> COD { get; set; }

    public virtual tblBrand tblBrand { get; set; }
    public virtual tblCategory tblCategory { get; set; }
    public virtual tblGender tblGender { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProductImage> tblProductImages { get; set; }
    public virtual tblSubCategory tblSubCategory { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProductSizeQuantity> tblProductSizeQuantities { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblrating> tblratings { get; set; }
}

public partial class tblProductImage
{
    public int PIMGID { get; set; }
    public Nullable<int> PID { get; set; }
    public string Name { get; set; }
    public string Extention { get; set; }

    public virtual tblProduct tblProduct { get; set; }
}

public partial class tblProductSizeQuantity
{
    public int PrdSizeQuantID { get; set; }
    public Nullable<int> PID { get; set; }
    public Nullable<int> SizeID { get; set; }
    public Nullable<int> Quantity { get; set; }

    public virtual tblProduct tblProduct { get; set; }
    public virtual tblSize tblSize { get; set; }
}

public partial class tblPurchase
{
    public int PurchaseID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string PIDSizeID { get; set; }
    public Nullable<decimal> CartAmount { get; set; }
    public Nullable<decimal> CartDiscount { get; set; }
    public Nullable<decimal> TotalPayed { get; set; }
    public string PaymentType { get; set; }
    public string PaymentStatus { get; set; }
    public Nullable<System.DateTime> DateOfPurchase { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public Nullable<int> PinCode { get; set; }
    public string MobileNumber { get; set; }

    public virtual User User { get; set; }
}

public partial class tblrating
{
    public int id { get; set; }
    public string review { get; set; }
    public Nullable<int> PID { get; set; }
    public Nullable<int> Uid { get; set; }

    public virtual tblProduct tblProduct { get; set; }
    public virtual User User { get; set; }
}

public partial class tblSize
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblSize()
    {
        this.tblProductSizeQuantities = new HashSet<tblProductSizeQuantity>();
    }

    public int SizeID { get; set; }
    public string SizeName { get; set; }
    public Nullable<int> BrandID { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public Nullable<int> SubCategoryID { get; set; }
    public Nullable<int> GenderID { get; set; }

    public virtual tblBrand tblBrand { get; set; }
    public virtual tblCategory tblCategory { get; set; }
    public virtual tblGender tblGender { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProductSizeQuantity> tblProductSizeQuantities { get; set; }
    public virtual tblSubCategory tblSubCategory { get; set; }
}

public partial class tblSubCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblSubCategory()
    {
        this.tblProducts = new HashSet<tblProduct>();
        this.tblSizes = new HashSet<tblSize>();
    }

    public int SubCatID { get; set; }
    public string SubCatName { get; set; }
    public Nullable<int> MainCatID { get; set; }

    public virtual tblCategory tblCategory { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProduct> tblProducts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblSize> tblSizes { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.tblPurchases = new HashSet<tblPurchase>();
        this.tblratings = new HashSet<tblrating>();
        this.ForgotPassRequests = new HashSet<ForgotPassRequest>();
    }

    public int Uid { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Name { get; set; }
    public string Usertype { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblPurchase> tblPurchases { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblrating> tblratings { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ForgotPassRequest> ForgotPassRequests { get; set; }
}
