//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ASPBOOTSTRAP3Entities : DbContext
{
    public ASPBOOTSTRAP3Entities()
        : base("name=ASPBOOTSTRAP3Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<company> companies { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<tblBrand> tblBrands { get; set; }
    public virtual DbSet<tblCategory> tblCategories { get; set; }
    public virtual DbSet<tblGender> tblGenders { get; set; }
    public virtual DbSet<tblProductImage> tblProductImages { get; set; }
    public virtual DbSet<tblProduct> tblProducts { get; set; }
    public virtual DbSet<tblProductSizeQuantity> tblProductSizeQuantities { get; set; }
    public virtual DbSet<tblPurchase> tblPurchases { get; set; }
    public virtual DbSet<tblrating> tblratings { get; set; }
    public virtual DbSet<tblSize> tblSizes { get; set; }
    public virtual DbSet<tblSubCategory> tblSubCategories { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<ForgotPassRequest> ForgotPassRequests { get; set; }
}
